name: "Southern Company Addon"
description: "This is an Addon to ingest data from the Southern Company (Georgia Power, Alabama Power, et cetera) APIs"
version: "1.0.0"
slug: "southern_company_api"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  username: "Your login username"
  password: "Your login password"